// Exercise library sourced from free-exercise-db (github.com/yuhonas/free-exercise-db),
// released under the Unlicense (public domain). 873 exercise names + muscle groups.
// Each is tagged with a pictogram category (see pictograms.jsx) — a small set of
// pose silhouettes covering the real movement patterns, since a photo shrunk to icon
// size just reads as noise. Free-text entry always stays available for anything not listed.

export const GROUPS = ['Chest', 'Back', 'Shoulders', 'Legs', 'Biceps', 'Triceps', 'Core', 'Cardio']

export const EXERCISES = [
  { name: 'Alternating Kettlebell Row', group: 'Back', pictogram: 'Row' },
  { name: 'Alternating Renegade Row', group: 'Back', pictogram: 'Row' },
  { name: 'Atlas Stone Trainer', group: 'Back', pictogram: 'Row' },
  { name: 'Atlas Stones', group: 'Back', pictogram: 'Row' },
  { name: 'Axle Deadlift', group: 'Back', pictogram: 'Hinge' },
  { name: 'Band Assisted Pull-Up', group: 'Back', pictogram: 'PullDown' },
  { name: 'Barbell Deadlift', group: 'Back', pictogram: 'Hinge' },
  { name: 'Bent Over Barbell Row', group: 'Back', pictogram: 'Row' },
  { name: 'Bent Over One-Arm Long Bar Row', group: 'Back', pictogram: 'Row' },
  { name: 'Bent Over Two-Arm Long Bar Row', group: 'Back', pictogram: 'Row' },
  { name: 'Bent Over Two-Dumbbell Row', group: 'Back', pictogram: 'Row' },
  { name: 'Bent Over Two-Dumbbell Row With Palms In', group: 'Back', pictogram: 'Row' },
  { name: 'Bent-Arm Barbell Pullover', group: 'Back', pictogram: 'Row' },
  { name: 'Bodyweight Mid Row', group: 'Back', pictogram: 'Row' },
  { name: 'Cable Incline Pushdown', group: 'Back', pictogram: 'Pushdown' },
  { name: 'Cat Stretch', group: 'Back', pictogram: 'Row' },
  { name: 'Catch and Overhead Throw', group: 'Back', pictogram: 'Row' },
  { name: 'Chair Lower Back Stretch', group: 'Back', pictogram: 'Row' },
  { name: 'Child\'s Pose', group: 'Back', pictogram: 'Row' },
  { name: 'Chin-Up', group: 'Back', pictogram: 'PullDown' },
  { name: 'Close-Grip Front Lat Pulldown', group: 'Back', pictogram: 'PullDown' },
  { name: 'Crossover Reverse Lunge', group: 'Back', pictogram: 'Lunge' },
  { name: 'Dancer\'s Stretch', group: 'Back', pictogram: 'Row' },
  { name: 'Deadlift with Bands', group: 'Back', pictogram: 'Hinge' },
  { name: 'Deadlift with Chains', group: 'Back', pictogram: 'Hinge' },
  { name: 'Deficit Deadlift', group: 'Back', pictogram: 'Hinge' },
  { name: 'Dumbbell Incline Row', group: 'Back', pictogram: 'Row' },
  { name: 'Dynamic Back Stretch', group: 'Back', pictogram: 'Row' },
  { name: 'Elevated Cable Rows', group: 'Back', pictogram: 'Row' },
  { name: 'Full Range-Of-Motion Lat Pulldown', group: 'Back', pictogram: 'PullDown' },
  { name: 'Gironda Sternum Chins', group: 'Back', pictogram: 'Row' },
  { name: 'Hug A Ball', group: 'Back', pictogram: 'Row' },
  { name: 'Hug Knees To Chest', group: 'Back', pictogram: 'Row' },
  { name: 'Hyperextensions (Back Extensions)', group: 'Back', pictogram: 'Row' },
  { name: 'Hyperextensions With No Hyperextension Bench', group: 'Back', pictogram: 'Row' },
  { name: 'Incline Bench Pull', group: 'Back', pictogram: 'Row' },
  { name: 'Inverted Row', group: 'Back', pictogram: 'Row' },
  { name: 'Inverted Row with Straps', group: 'Back', pictogram: 'Row' },
  { name: 'Keg Load', group: 'Back', pictogram: 'Row' },
  { name: 'Kipping Muscle Up', group: 'Back', pictogram: 'Row' },
  { name: 'Kneeling High Pulley Row', group: 'Back', pictogram: 'Row' },
  { name: 'Kneeling Single-Arm High Pulley Row', group: 'Back', pictogram: 'Row' },
  { name: 'Latissimus Dorsi-SMR', group: 'Back', pictogram: 'Row' },
  { name: 'Leverage High Row', group: 'Back', pictogram: 'Row' },
  { name: 'Leverage Iso Row', group: 'Back', pictogram: 'Row' },
  { name: 'London Bridges', group: 'Back', pictogram: 'Row' },
  { name: 'Lower Back-SMR', group: 'Back', pictogram: 'Row' },
  { name: 'Lying Cambered Barbell Row', group: 'Back', pictogram: 'Row' },
  { name: 'Lying T-Bar Row', group: 'Back', pictogram: 'Row' },
  { name: 'Middle Back Shrug', group: 'Back', pictogram: 'Shrug' },
  { name: 'Middle Back Stretch', group: 'Back', pictogram: 'Row' },
  { name: 'Mixed Grip Chin', group: 'Back', pictogram: 'Row' },
  { name: 'Muscle Up', group: 'Back', pictogram: 'Row' },
  { name: 'One Arm Against Wall', group: 'Back', pictogram: 'Row' },
  { name: 'One Arm Chin-Up', group: 'Back', pictogram: 'PullDown' },
  { name: 'One Arm Lat Pulldown', group: 'Back', pictogram: 'PullDown' },
  { name: 'One Handed Hang', group: 'Back', pictogram: 'Row' },
  { name: 'One-Arm Dumbbell Row', group: 'Back', pictogram: 'Row' },
  { name: 'One-Arm Kettlebell Row', group: 'Back', pictogram: 'Row' },
  { name: 'One-Arm Long Bar Row', group: 'Back', pictogram: 'Row' },
  { name: 'Overhead Lat', group: 'Back', pictogram: 'Row' },
  { name: 'Overhead Slam', group: 'Back', pictogram: 'Row' },
  { name: 'Pelvic Tilt Into Bridge', group: 'Back', pictogram: 'Row' },
  { name: 'Pullups', group: 'Back', pictogram: 'PullDown' },
  { name: 'Pyramid', group: 'Back', pictogram: 'Row' },
  { name: 'Rack Pull with Bands', group: 'Back', pictogram: 'Row' },
  { name: 'Rack Pulls', group: 'Back', pictogram: 'Row' },
  { name: 'Reverse Band Deadlift', group: 'Back', pictogram: 'Hinge' },
  { name: 'Reverse Grip Bent-Over Rows', group: 'Back', pictogram: 'Row' },
  { name: 'Rhomboids-SMR', group: 'Back', pictogram: 'Row' },
  { name: 'Rocky Pull-Ups/Pulldowns', group: 'Back', pictogram: 'PullDown' },
  { name: 'Rope Climb', group: 'Back', pictogram: 'Row' },
  { name: 'Rope Straight-Arm Pulldown', group: 'Back', pictogram: 'PullDown' },
  { name: 'Seated Cable Rows', group: 'Back', pictogram: 'Row' },
  { name: 'Seated Good Mornings', group: 'Back', pictogram: 'Hinge' },
  { name: 'Seated One-arm Cable Pulley Rows', group: 'Back', pictogram: 'Row' },
  { name: 'Shotgun Row', group: 'Back', pictogram: 'Row' },
  { name: 'Side To Side Chins', group: 'Back', pictogram: 'Row' },
  { name: 'Side-Lying Floor Stretch', group: 'Back', pictogram: 'Row' },
  { name: 'Sled Row', group: 'Back', pictogram: 'Row' },
  { name: 'Smith Machine Bent Over Row', group: 'Back', pictogram: 'Row' },
  { name: 'Spinal Stretch', group: 'Back', pictogram: 'Row' },
  { name: 'Standing Pelvic Tilt', group: 'Back', pictogram: 'Row' },
  { name: 'Stiff Leg Barbell Good Morning', group: 'Back', pictogram: 'Hinge' },
  { name: 'Straight Bar Bench Mid Rows', group: 'Back', pictogram: 'Row' },
  { name: 'Straight-Arm Pulldown', group: 'Back', pictogram: 'PullDown' },
  { name: 'Superman', group: 'Back', pictogram: 'Row' },
  { name: 'Suspended Row', group: 'Back', pictogram: 'Row' },
  { name: 'T-Bar Row with Handle', group: 'Back', pictogram: 'Row' },
  { name: 'Two-Arm Kettlebell Row', group: 'Back', pictogram: 'Row' },
  { name: 'Underhand Cable Pulldowns', group: 'Back', pictogram: 'PullDown' },
  { name: 'Upper Back Stretch', group: 'Back', pictogram: 'Row' },
  { name: 'V-Bar Pulldown', group: 'Back', pictogram: 'PullDown' },
  { name: 'V-Bar Pullup', group: 'Back', pictogram: 'PullDown' },
  { name: 'Weighted Ball Hyperextension', group: 'Back', pictogram: 'Row' },
  { name: 'Weighted Pull Ups', group: 'Back', pictogram: 'Row' },
  { name: 'Wide-Grip Lat Pulldown', group: 'Back', pictogram: 'PullDown' },
  { name: 'Wide-Grip Pulldown Behind The Neck', group: 'Back', pictogram: 'PullDown' },
  { name: 'Wide-Grip Rear Pull-Up', group: 'Back', pictogram: 'PullDown' },
  { name: 'Alternate Hammer Curl', group: 'Biceps', pictogram: 'Curl' },
  { name: 'Alternate Incline Dumbbell Curl', group: 'Biceps', pictogram: 'Curl' },
  { name: 'Barbell Curl', group: 'Biceps', pictogram: 'Curl' },
  { name: 'Barbell Curls Lying Against An Incline', group: 'Biceps', pictogram: 'Curl' },
  { name: 'Bottoms-Up Clean From The Hang Position', group: 'Biceps', pictogram: 'Curl' },
  { name: 'Brachialis-SMR', group: 'Biceps', pictogram: 'Curl' },
  { name: 'Cable Hammer Curls - Rope Attachment', group: 'Biceps', pictogram: 'Curl' },
  { name: 'Cable Preacher Curl', group: 'Biceps', pictogram: 'Curl' },
  { name: 'Cable Wrist Curl', group: 'Biceps', pictogram: 'Curl' },
  { name: 'Close-Grip EZ Bar Curl', group: 'Biceps', pictogram: 'Curl' },
  { name: 'Close-Grip EZ-Bar Curl with Band', group: 'Biceps', pictogram: 'Curl' },
  { name: 'Close-Grip Standing Barbell Curl', group: 'Biceps', pictogram: 'Curl' },
  { name: 'Concentration Curls', group: 'Biceps', pictogram: 'Curl' },
  { name: 'Cross Body Hammer Curl', group: 'Biceps', pictogram: 'Curl' },
  { name: 'Drag Curl', group: 'Biceps', pictogram: 'Curl' },
  { name: 'Dumbbell Alternate Bicep Curl', group: 'Biceps', pictogram: 'Curl' },
  { name: 'Dumbbell Bicep Curl', group: 'Biceps', pictogram: 'Curl' },
  { name: 'Dumbbell Lying Pronation', group: 'Biceps', pictogram: 'Curl' },
  { name: 'Dumbbell Lying Supination', group: 'Biceps', pictogram: 'Curl' },
  { name: 'Dumbbell Prone Incline Curl', group: 'Biceps', pictogram: 'Curl' },
  { name: 'EZ-Bar Curl', group: 'Biceps', pictogram: 'Curl' },
  { name: 'Farmer\'s Walk', group: 'Biceps', pictogram: 'Curl' },
  { name: 'Finger Curls', group: 'Biceps', pictogram: 'Curl' },
  { name: 'Flexor Incline Dumbbell Curls', group: 'Biceps', pictogram: 'Curl' },
  { name: 'Hammer Curls', group: 'Biceps', pictogram: 'Curl' },
  { name: 'High Cable Curls', group: 'Biceps', pictogram: 'Curl' },
  { name: 'Incline Dumbbell Curl', group: 'Biceps', pictogram: 'Curl' },
  { name: 'Incline Hammer Curls', group: 'Biceps', pictogram: 'Curl' },
  { name: 'Incline Inner Biceps Curl', group: 'Biceps', pictogram: 'Curl' },
  { name: 'Kneeling Forearm Stretch', group: 'Biceps', pictogram: 'Curl' },
  { name: 'Lying Cable Curl', group: 'Biceps', pictogram: 'Curl' },
  { name: 'Lying Close-Grip Bar Curl On High Pulley', group: 'Biceps', pictogram: 'Curl' },
  { name: 'Lying High Bench Barbell Curl', group: 'Biceps', pictogram: 'Curl' },
  { name: 'Lying Supine Dumbbell Curl', group: 'Biceps', pictogram: 'Curl' },
  { name: 'Machine Bicep Curl', group: 'Biceps', pictogram: 'Curl' },
  { name: 'Machine Preacher Curls', group: 'Biceps', pictogram: 'Curl' },
  { name: 'One Arm Dumbbell Preacher Curl', group: 'Biceps', pictogram: 'Curl' },
  { name: 'Overhead Cable Curl', group: 'Biceps', pictogram: 'Curl' },
  { name: 'Palms-Down Dumbbell Wrist Curl Over A Bench', group: 'Biceps', pictogram: 'Curl' },
  { name: 'Palms-Down Wrist Curl Over A Bench', group: 'Biceps', pictogram: 'Curl' },
  { name: 'Palms-Up Barbell Wrist Curl Over A Bench', group: 'Biceps', pictogram: 'Curl' },
  { name: 'Palms-Up Dumbbell Wrist Curl Over A Bench', group: 'Biceps', pictogram: 'Curl' },
  { name: 'Plate Pinch', group: 'Biceps', pictogram: 'Curl' },
  { name: 'Preacher Curl', group: 'Biceps', pictogram: 'Curl' },
  { name: 'Preacher Hammer Dumbbell Curl', group: 'Biceps', pictogram: 'Curl' },
  { name: 'Reverse Barbell Curl', group: 'Biceps', pictogram: 'Curl' },
  { name: 'Reverse Barbell Preacher Curls', group: 'Biceps', pictogram: 'Curl' },
  { name: 'Reverse Cable Curl', group: 'Biceps', pictogram: 'Curl' },
  { name: 'Reverse Plate Curls', group: 'Biceps', pictogram: 'Curl' },
  { name: 'Rickshaw Carry', group: 'Biceps', pictogram: 'Curl' },
  { name: 'Seated Biceps', group: 'Biceps', pictogram: 'Curl' },
  { name: 'Seated Close-Grip Concentration Barbell Curl', group: 'Biceps', pictogram: 'Curl' },
  { name: 'Seated Dumbbell Curl', group: 'Biceps', pictogram: 'Curl' },
  { name: 'Seated Dumbbell Inner Biceps Curl', group: 'Biceps', pictogram: 'Curl' },
  { name: 'Seated Dumbbell Palms-Down Wrist Curl', group: 'Biceps', pictogram: 'Curl' },
  { name: 'Seated Dumbbell Palms-Up Wrist Curl', group: 'Biceps', pictogram: 'Curl' },
  { name: 'Seated One-Arm Dumbbell Palms-Down Wrist Curl', group: 'Biceps', pictogram: 'Curl' },
  { name: 'Seated One-Arm Dumbbell Palms-Up Wrist Curl', group: 'Biceps', pictogram: 'Curl' },
  { name: 'Seated Palm-Up Barbell Wrist Curl', group: 'Biceps', pictogram: 'Curl' },
  { name: 'Seated Palms-Down Barbell Wrist Curl', group: 'Biceps', pictogram: 'Curl' },
  { name: 'Seated Two-Arm Palms-Up Low-Pulley Wrist Curl', group: 'Biceps', pictogram: 'Curl' },
  { name: 'Spider Curl', group: 'Biceps', pictogram: 'Curl' },
  { name: 'Standing Biceps Cable Curl', group: 'Biceps', pictogram: 'Curl' },
  { name: 'Standing Biceps Stretch', group: 'Biceps', pictogram: 'Curl' },
  { name: 'Standing Concentration Curl', group: 'Biceps', pictogram: 'Curl' },
  { name: 'Standing Dumbbell Reverse Curl', group: 'Biceps', pictogram: 'Curl' },
  { name: 'Standing Inner-Biceps Curl', group: 'Biceps', pictogram: 'Curl' },
  { name: 'Standing Olympic Plate Hand Squeeze', group: 'Biceps', pictogram: 'Curl' },
  { name: 'Standing One-Arm Cable Curl', group: 'Biceps', pictogram: 'Curl' },
  { name: 'Standing One-Arm Dumbbell Curl Over Incline Bench', group: 'Biceps', pictogram: 'Curl' },
  { name: 'Standing Palms-Up Barbell Behind The Back Wrist Curl', group: 'Biceps', pictogram: 'Curl' },
  { name: 'Two-Arm Dumbbell Preacher Curl', group: 'Biceps', pictogram: 'Curl' },
  { name: 'Wide-Grip Standing Barbell Curl', group: 'Biceps', pictogram: 'Curl' },
  { name: 'Wrist Circles', group: 'Biceps', pictogram: 'Curl' },
  { name: 'Wrist Roller', group: 'Biceps', pictogram: 'Curl' },
  { name: 'Wrist Rotations with Straight Bar', group: 'Biceps', pictogram: 'Twist' },
  { name: 'Zottman Curl', group: 'Biceps', pictogram: 'Curl' },
  { name: 'Zottman Preacher Curl', group: 'Biceps', pictogram: 'Curl' },
  { name: 'Bicycling', group: 'Cardio', pictogram: 'Cardio' },
  { name: 'Bicycling, Stationary', group: 'Cardio', pictogram: 'Cardio' },
  { name: 'Elliptical Trainer', group: 'Cardio', pictogram: 'Cardio' },
  { name: 'Jogging, Treadmill', group: 'Cardio', pictogram: 'Cardio' },
  { name: 'Prowler Sprint', group: 'Cardio', pictogram: 'Row' },
  { name: 'Recumbent Bike', group: 'Cardio', pictogram: 'Cardio' },
  { name: 'Rope Jumping', group: 'Cardio', pictogram: 'Cardio' },
  { name: 'Rowing, Stationary', group: 'Cardio', pictogram: 'Row' },
  { name: 'Running, Treadmill', group: 'Cardio', pictogram: 'Cardio' },
  { name: 'Skating', group: 'Cardio', pictogram: 'Cardio' },
  { name: 'Stairmaster', group: 'Cardio', pictogram: 'Cardio' },
  { name: 'Step Mill', group: 'Cardio', pictogram: 'Cardio' },
  { name: 'Trail Running/Walking', group: 'Cardio', pictogram: 'Cardio' },
  { name: 'Walking, Treadmill', group: 'Cardio', pictogram: 'Cardio' },
  { name: 'Alternating Floor Press', group: 'Chest', pictogram: 'Press' },
  { name: 'Around The Worlds', group: 'Chest', pictogram: 'Press' },
  { name: 'Barbell Bench Press - Medium Grip', group: 'Chest', pictogram: 'Press' },
  { name: 'Barbell Guillotine Bench Press', group: 'Chest', pictogram: 'Press' },
  { name: 'Barbell Incline Bench Press - Medium Grip', group: 'Chest', pictogram: 'Press' },
  { name: 'Behind Head Chest Stretch', group: 'Chest', pictogram: 'Press' },
  { name: 'Bench Press - With Bands', group: 'Chest', pictogram: 'Press' },
  { name: 'Bent-Arm Dumbbell Pullover', group: 'Chest', pictogram: 'Press' },
  { name: 'Bodyweight Flyes', group: 'Chest', pictogram: 'Fly' },
  { name: 'Butterfly', group: 'Chest', pictogram: 'Fly' },
  { name: 'Cable Chest Press', group: 'Chest', pictogram: 'Press' },
  { name: 'Cable Crossover', group: 'Chest', pictogram: 'Fly' },
  { name: 'Cable Iron Cross', group: 'Chest', pictogram: 'Press' },
  { name: 'Chain Press', group: 'Chest', pictogram: 'Press' },
  { name: 'Chest And Front Of Shoulder Stretch', group: 'Chest', pictogram: 'Press' },
  { name: 'Chest Push (multiple response)', group: 'Chest', pictogram: 'Press' },
  { name: 'Chest Push (single response)', group: 'Chest', pictogram: 'Press' },
  { name: 'Chest Push from 3 point stance', group: 'Chest', pictogram: 'Press' },
  { name: 'Chest Push with Run Release', group: 'Chest', pictogram: 'Cardio' },
  { name: 'Chest Stretch on Stability Ball', group: 'Chest', pictogram: 'Press' },
  { name: 'Clock Push-Up', group: 'Chest', pictogram: 'PushUp' },
  { name: 'Cross Over - With Bands', group: 'Chest', pictogram: 'Press' },
  { name: 'Decline Barbell Bench Press', group: 'Chest', pictogram: 'Press' },
  { name: 'Decline Dumbbell Bench Press', group: 'Chest', pictogram: 'Press' },
  { name: 'Decline Dumbbell Flyes', group: 'Chest', pictogram: 'Fly' },
  { name: 'Decline Push-Up', group: 'Chest', pictogram: 'PushUp' },
  { name: 'Decline Smith Press', group: 'Chest', pictogram: 'Press' },
  { name: 'Dips - Chest Version', group: 'Chest', pictogram: 'Press' },
  { name: 'Drop Push', group: 'Chest', pictogram: 'Press' },
  { name: 'Dumbbell Bench Press', group: 'Chest', pictogram: 'Press' },
  { name: 'Dumbbell Bench Press with Neutral Grip', group: 'Chest', pictogram: 'Press' },
  { name: 'Dumbbell Flyes', group: 'Chest', pictogram: 'Fly' },
  { name: 'Dynamic Chest Stretch', group: 'Chest', pictogram: 'Press' },
  { name: 'Elbows Back', group: 'Chest', pictogram: 'Press' },
  { name: 'Extended Range One-Arm Kettlebell Floor Press', group: 'Chest', pictogram: 'Press' },
  { name: 'Flat Bench Cable Flyes', group: 'Chest', pictogram: 'Fly' },
  { name: 'Forward Drag with Press', group: 'Chest', pictogram: 'Press' },
  { name: 'Front Raise And Pullover', group: 'Chest', pictogram: 'FrontRaise' },
  { name: 'Hammer Grip Incline DB Bench Press', group: 'Chest', pictogram: 'Press' },
  { name: 'Heavy Bag Thrust', group: 'Chest', pictogram: 'Press' },
  { name: 'Incline Cable Chest Press', group: 'Chest', pictogram: 'Press' },
  { name: 'Incline Cable Flye', group: 'Chest', pictogram: 'Fly' },
  { name: 'Incline Dumbbell Bench With Palms Facing In', group: 'Chest', pictogram: 'Press' },
  { name: 'Incline Dumbbell Flyes', group: 'Chest', pictogram: 'Fly' },
  { name: 'Incline Dumbbell Flyes - With A Twist', group: 'Chest', pictogram: 'Fly' },
  { name: 'Incline Dumbbell Press', group: 'Chest', pictogram: 'Press' },
  { name: 'Incline Push-Up', group: 'Chest', pictogram: 'PushUp' },
  { name: 'Incline Push-Up Depth Jump', group: 'Chest', pictogram: 'PushUp' },
  { name: 'Incline Push-Up Medium', group: 'Chest', pictogram: 'PushUp' },
  { name: 'Incline Push-Up Reverse Grip', group: 'Chest', pictogram: 'PushUp' },
  { name: 'Incline Push-Up Wide', group: 'Chest', pictogram: 'PushUp' },
  { name: 'Isometric Chest Squeezes', group: 'Chest', pictogram: 'Press' },
  { name: 'Isometric Wipers', group: 'Chest', pictogram: 'Press' },
  { name: 'Leg-Over Floor Press', group: 'Chest', pictogram: 'Press' },
  { name: 'Leverage Chest Press', group: 'Chest', pictogram: 'Press' },
  { name: 'Leverage Decline Chest Press', group: 'Chest', pictogram: 'Press' },
  { name: 'Leverage Incline Chest Press', group: 'Chest', pictogram: 'Press' },
  { name: 'Low Cable Crossover', group: 'Chest', pictogram: 'Fly' },
  { name: 'Machine Bench Press', group: 'Chest', pictogram: 'Press' },
  { name: 'Medicine Ball Chest Pass', group: 'Chest', pictogram: 'Press' },
  { name: 'Neck Press', group: 'Chest', pictogram: 'Press' },
  { name: 'One Arm Dumbbell Bench Press', group: 'Chest', pictogram: 'Press' },
  { name: 'One-Arm Flat Bench Dumbbell Flye', group: 'Chest', pictogram: 'Fly' },
  { name: 'One-Arm Kettlebell Floor Press', group: 'Chest', pictogram: 'Press' },
  { name: 'Plyo Kettlebell Pushups', group: 'Chest', pictogram: 'PushUp' },
  { name: 'Plyo Push-up', group: 'Chest', pictogram: 'PushUp' },
  { name: 'Push Up to Side Plank', group: 'Chest', pictogram: 'PushUp' },
  { name: 'Push-Up Wide', group: 'Chest', pictogram: 'PushUp' },
  { name: 'Push-Ups With Feet Elevated', group: 'Chest', pictogram: 'PushUp' },
  { name: 'Push-Ups With Feet On An Exercise Ball', group: 'Chest', pictogram: 'PushUp' },
  { name: 'Pushups', group: 'Chest', pictogram: 'PushUp' },
  { name: 'Pushups (Close and Wide Hand Positions)', group: 'Chest', pictogram: 'PushUp' },
  { name: 'Single-Arm Cable Crossover', group: 'Chest', pictogram: 'Fly' },
  { name: 'Single-Arm Push-Up', group: 'Chest', pictogram: 'PushUp' },
  { name: 'Smith Machine Bench Press', group: 'Chest', pictogram: 'Press' },
  { name: 'Smith Machine Decline Press', group: 'Chest', pictogram: 'Press' },
  { name: 'Smith Machine Incline Bench Press', group: 'Chest', pictogram: 'Press' },
  { name: 'Standing Cable Chest Press', group: 'Chest', pictogram: 'Press' },
  { name: 'Straight-Arm Dumbbell Pullover', group: 'Chest', pictogram: 'Press' },
  { name: 'Suspended Push-Up', group: 'Chest', pictogram: 'PushUp' },
  { name: 'Svend Press', group: 'Chest', pictogram: 'Press' },
  { name: 'Wide-Grip Barbell Bench Press', group: 'Chest', pictogram: 'Press' },
  { name: 'Wide-Grip Decline Barbell Bench Press', group: 'Chest', pictogram: 'Press' },
  { name: 'Wide-Grip Decline Barbell Pullover', group: 'Chest', pictogram: 'Press' },
  { name: '3/4 Sit-Up', group: 'Core', pictogram: 'Crunch' },
  { name: 'Ab Crunch Machine', group: 'Core', pictogram: 'Crunch' },
  { name: 'Ab Roller', group: 'Core', pictogram: 'Plank' },
  { name: 'Advanced Kettlebell Windmill', group: 'Core', pictogram: 'Plank' },
  { name: 'Air Bike', group: 'Core', pictogram: 'Cardio' },
  { name: 'Alternate Heel Touchers', group: 'Core', pictogram: 'Plank' },
  { name: 'Barbell Ab Rollout', group: 'Core', pictogram: 'Plank' },
  { name: 'Barbell Ab Rollout - On Knees', group: 'Core', pictogram: 'Plank' },
  { name: 'Barbell Rollout from Bench', group: 'Core', pictogram: 'Plank' },
  { name: 'Barbell Side Bend', group: 'Core', pictogram: 'Plank' },
  { name: 'Bent Press', group: 'Core', pictogram: 'Plank' },
  { name: 'Bent-Knee Hip Raise', group: 'Core', pictogram: 'Plank' },
  { name: 'Bosu Ball Cable Crunch With Side Bends', group: 'Core', pictogram: 'Crunch' },
  { name: 'Bottoms Up', group: 'Core', pictogram: 'Plank' },
  { name: 'Butt-Ups', group: 'Core', pictogram: 'Plank' },
  { name: 'Cable Crunch', group: 'Core', pictogram: 'Crunch' },
  { name: 'Cable Judo Flip', group: 'Core', pictogram: 'Plank' },
  { name: 'Cable Reverse Crunch', group: 'Core', pictogram: 'Crunch' },
  { name: 'Cable Russian Twists', group: 'Core', pictogram: 'Twist' },
  { name: 'Cable Seated Crunch', group: 'Core', pictogram: 'Crunch' },
  { name: 'Cocoons', group: 'Core', pictogram: 'Plank' },
  { name: 'Cross-Body Crunch', group: 'Core', pictogram: 'Crunch' },
  { name: 'Crunch - Hands Overhead', group: 'Core', pictogram: 'Crunch' },
  { name: 'Crunch - Legs On Exercise Ball', group: 'Core', pictogram: 'Crunch' },
  { name: 'Crunches', group: 'Core', pictogram: 'Crunch' },
  { name: 'Dead Bug', group: 'Core', pictogram: 'Plank' },
  { name: 'Decline Crunch', group: 'Core', pictogram: 'Crunch' },
  { name: 'Decline Oblique Crunch', group: 'Core', pictogram: 'Crunch' },
  { name: 'Decline Reverse Crunch', group: 'Core', pictogram: 'Crunch' },
  { name: 'Double Kettlebell Windmill', group: 'Core', pictogram: 'Plank' },
  { name: 'Dumbbell Side Bend', group: 'Core', pictogram: 'Plank' },
  { name: 'Elbow to Knee', group: 'Core', pictogram: 'Plank' },
  { name: 'Exercise Ball Crunch', group: 'Core', pictogram: 'Crunch' },
  { name: 'Exercise Ball Pull-In', group: 'Core', pictogram: 'Plank' },
  { name: 'Flat Bench Leg Pull-In', group: 'Core', pictogram: 'Plank' },
  { name: 'Flat Bench Lying Leg Raise', group: 'Core', pictogram: 'LegRaise' },
  { name: 'Frog Sit-Ups', group: 'Core', pictogram: 'Crunch' },
  { name: 'Gorilla Chin/Crunch', group: 'Core', pictogram: 'Crunch' },
  { name: 'Hanging Leg Raise', group: 'Core', pictogram: 'LegRaise' },
  { name: 'Hanging Pike', group: 'Core', pictogram: 'Plank' },
  { name: 'Jackknife Sit-Up', group: 'Core', pictogram: 'Crunch' },
  { name: 'Janda Sit-Up', group: 'Core', pictogram: 'Crunch' },
  { name: 'Kettlebell Figure 8', group: 'Core', pictogram: 'Plank' },
  { name: 'Kettlebell Pass Between The Legs', group: 'Core', pictogram: 'Plank' },
  { name: 'Kettlebell Windmill', group: 'Core', pictogram: 'Plank' },
  { name: 'Knee/Hip Raise On Parallel Bars', group: 'Core', pictogram: 'Plank' },
  { name: 'Kneeling Cable Crunch With Alternating Oblique Twists', group: 'Core', pictogram: 'Crunch' },
  { name: 'Landmine 180\'s', group: 'Core', pictogram: 'Plank' },
  { name: 'Leg Pull-In', group: 'Core', pictogram: 'Plank' },
  { name: 'Lower Back Curl', group: 'Core', pictogram: 'Curl' },
  { name: 'Medicine Ball Full Twist', group: 'Core', pictogram: 'Twist' },
  { name: 'Oblique Crunches', group: 'Core', pictogram: 'Crunch' },
  { name: 'Oblique Crunches - On The Floor', group: 'Core', pictogram: 'Crunch' },
  { name: 'One-Arm High-Pulley Cable Side Bends', group: 'Core', pictogram: 'Plank' },
  { name: 'One-Arm Medicine Ball Slam', group: 'Core', pictogram: 'Plank' },
  { name: 'Otis-Up', group: 'Core', pictogram: 'Plank' },
  { name: 'Overhead Stretch', group: 'Core', pictogram: 'Plank' },
  { name: 'Pallof Press', group: 'Core', pictogram: 'Plank' },
  { name: 'Pallof Press With Rotation', group: 'Core', pictogram: 'Twist' },
  { name: 'Plank', group: 'Core', pictogram: 'Plank' },
  { name: 'Plate Twist', group: 'Core', pictogram: 'Twist' },
  { name: 'Press Sit-Up', group: 'Core', pictogram: 'Crunch' },
  { name: 'Reverse Crunch', group: 'Core', pictogram: 'Crunch' },
  { name: 'Rope Crunch', group: 'Core', pictogram: 'Crunch' },
  { name: 'Russian Twist', group: 'Core', pictogram: 'Twist' },
  { name: 'Scissor Kick', group: 'Core', pictogram: 'Plank' },
  { name: 'Seated Barbell Twist', group: 'Core', pictogram: 'Twist' },
  { name: 'Seated Flat Bench Leg Pull-In', group: 'Core', pictogram: 'Plank' },
  { name: 'Seated Leg Tucks', group: 'Core', pictogram: 'Plank' },
  { name: 'Seated Overhead Stretch', group: 'Core', pictogram: 'Plank' },
  { name: 'Side Bridge', group: 'Core', pictogram: 'Plank' },
  { name: 'Side Jackknife', group: 'Core', pictogram: 'Plank' },
  { name: 'Sit-Up', group: 'Core', pictogram: 'Crunch' },
  { name: 'Sledgehammer Swings', group: 'Core', pictogram: 'Cardio' },
  { name: 'Smith Machine Hip Raise', group: 'Core', pictogram: 'Plank' },
  { name: 'Spell Caster', group: 'Core', pictogram: 'Plank' },
  { name: 'Spider Crawl', group: 'Core', pictogram: 'Plank' },
  { name: 'Standing Cable Lift', group: 'Core', pictogram: 'Plank' },
  { name: 'Standing Cable Wood Chop', group: 'Core', pictogram: 'Plank' },
  { name: 'Standing Lateral Stretch', group: 'Core', pictogram: 'Plank' },
  { name: 'Standing Rope Crunch', group: 'Core', pictogram: 'Crunch' },
  { name: 'Stomach Vacuum', group: 'Core', pictogram: 'Plank' },
  { name: 'Supine One-Arm Overhead Throw', group: 'Core', pictogram: 'Row' },
  { name: 'Supine Two-Arm Overhead Throw', group: 'Core', pictogram: 'Row' },
  { name: 'Suspended Fallout', group: 'Core', pictogram: 'Plank' },
  { name: 'Suspended Reverse Crunch', group: 'Core', pictogram: 'Crunch' },
  { name: 'Toe Touchers', group: 'Core', pictogram: 'Plank' },
  { name: 'Torso Rotation', group: 'Core', pictogram: 'Twist' },
  { name: 'Tuck Crunch', group: 'Core', pictogram: 'Crunch' },
  { name: 'Weighted Ball Side Bend', group: 'Core', pictogram: 'Plank' },
  { name: 'Weighted Crunches', group: 'Core', pictogram: 'Crunch' },
  { name: 'Weighted Sit-Ups - With Bands', group: 'Core', pictogram: 'Crunch' },
  { name: 'Wind Sprints', group: 'Core', pictogram: 'Plank' },
  { name: '90/90 Hamstring', group: 'Legs', pictogram: 'Squat' },
  { name: 'Adductor', group: 'Legs', pictogram: 'Squat' },
  { name: 'Adductor/Groin', group: 'Legs', pictogram: 'Squat' },
  { name: 'All Fours Quad Stretch', group: 'Legs', pictogram: 'Squat' },
  { name: 'Alternate Leg Diagonal Bound', group: 'Legs', pictogram: 'Squat' },
  { name: 'Alternating Hang Clean', group: 'Legs', pictogram: 'Squat' },
  { name: 'Ankle Circles', group: 'Legs', pictogram: 'Squat' },
  { name: 'Ankle On The Knee', group: 'Legs', pictogram: 'Squat' },
  { name: 'Anterior Tibialis-SMR', group: 'Legs', pictogram: 'Squat' },
  { name: 'Backward Drag', group: 'Legs', pictogram: 'Squat' },
  { name: 'Balance Board', group: 'Legs', pictogram: 'Squat' },
  { name: 'Ball Leg Curl', group: 'Legs', pictogram: 'LegCurl' },
  { name: 'Band Good Morning', group: 'Legs', pictogram: 'Hinge' },
  { name: 'Band Good Morning (Pull Through)', group: 'Legs', pictogram: 'Hinge' },
  { name: 'Band Hip Adductions', group: 'Legs', pictogram: 'Squat' },
  { name: 'Barbell Full Squat', group: 'Legs', pictogram: 'Squat' },
  { name: 'Barbell Glute Bridge', group: 'Legs', pictogram: 'Hinge' },
  { name: 'Barbell Hack Squat', group: 'Legs', pictogram: 'Squat' },
  { name: 'Barbell Hip Thrust', group: 'Legs', pictogram: 'Hinge' },
  { name: 'Barbell Lunge', group: 'Legs', pictogram: 'Lunge' },
  { name: 'Barbell Seated Calf Raise', group: 'Legs', pictogram: 'Calf' },
  { name: 'Barbell Side Split Squat', group: 'Legs', pictogram: 'Squat' },
  { name: 'Barbell Squat', group: 'Legs', pictogram: 'Squat' },
  { name: 'Barbell Squat To A Bench', group: 'Legs', pictogram: 'Squat' },
  { name: 'Barbell Step Ups', group: 'Legs', pictogram: 'Lunge' },
  { name: 'Barbell Walking Lunge', group: 'Legs', pictogram: 'Lunge' },
  { name: 'Bear Crawl Sled Drags', group: 'Legs', pictogram: 'Cardio' },
  { name: 'Bench Jump', group: 'Legs', pictogram: 'Squat' },
  { name: 'Bench Sprint', group: 'Legs', pictogram: 'Squat' },
  { name: 'Bodyweight Squat', group: 'Legs', pictogram: 'Squat' },
  { name: 'Bodyweight Walking Lunge', group: 'Legs', pictogram: 'Lunge' },
  { name: 'Box Jump (Multiple Response)', group: 'Legs', pictogram: 'Squat' },
  { name: 'Box Skip', group: 'Legs', pictogram: 'Squat' },
  { name: 'Box Squat', group: 'Legs', pictogram: 'Squat' },
  { name: 'Box Squat with Bands', group: 'Legs', pictogram: 'Squat' },
  { name: 'Box Squat with Chains', group: 'Legs', pictogram: 'Squat' },
  { name: 'Butt Lift (Bridge)', group: 'Legs', pictogram: 'Squat' },
  { name: 'Cable Deadlifts', group: 'Legs', pictogram: 'Hinge' },
  { name: 'Cable Hip Adduction', group: 'Legs', pictogram: 'Squat' },
  { name: 'Calf Press', group: 'Legs', pictogram: 'Calf' },
  { name: 'Calf Press On The Leg Press Machine', group: 'Legs', pictogram: 'LegPress' },
  { name: 'Calf Raise On A Dumbbell', group: 'Legs', pictogram: 'Calf' },
  { name: 'Calf Raises - With Bands', group: 'Legs', pictogram: 'Calf' },
  { name: 'Calf Stretch Elbows Against Wall', group: 'Legs', pictogram: 'Calf' },
  { name: 'Calf Stretch Hands Against Wall', group: 'Legs', pictogram: 'Calf' },
  { name: 'Calves-SMR', group: 'Legs', pictogram: 'Squat' },
  { name: 'Car Deadlift', group: 'Legs', pictogram: 'Hinge' },
  { name: 'Carioca Quick Step', group: 'Legs', pictogram: 'Squat' },
  { name: 'Chair Leg Extended Stretch', group: 'Legs', pictogram: 'Squat' },
  { name: 'Chair Squat', group: 'Legs', pictogram: 'Squat' },
  { name: 'Clean', group: 'Legs', pictogram: 'Squat' },
  { name: 'Clean Deadlift', group: 'Legs', pictogram: 'Hinge' },
  { name: 'Clean Pull', group: 'Legs', pictogram: 'Squat' },
  { name: 'Clean from Blocks', group: 'Legs', pictogram: 'Squat' },
  { name: 'Conan\'s Wheel', group: 'Legs', pictogram: 'Squat' },
  { name: 'Depth Jump Leap', group: 'Legs', pictogram: 'Squat' },
  { name: 'Donkey Calf Raises', group: 'Legs', pictogram: 'Calf' },
  { name: 'Double Kettlebell Alternating Hang Clean', group: 'Legs', pictogram: 'Squat' },
  { name: 'Double Leg Butt Kick', group: 'Legs', pictogram: 'Squat' },
  { name: 'Downward Facing Balance', group: 'Legs', pictogram: 'Squat' },
  { name: 'Dumbbell Clean', group: 'Legs', pictogram: 'Squat' },
  { name: 'Dumbbell Lunges', group: 'Legs', pictogram: 'Lunge' },
  { name: 'Dumbbell Rear Lunge', group: 'Legs', pictogram: 'Lunge' },
  { name: 'Dumbbell Seated Box Jump', group: 'Legs', pictogram: 'Squat' },
  { name: 'Dumbbell Seated One-Leg Calf Raise', group: 'Legs', pictogram: 'Calf' },
  { name: 'Dumbbell Squat', group: 'Legs', pictogram: 'Squat' },
  { name: 'Dumbbell Squat To A Bench', group: 'Legs', pictogram: 'Squat' },
  { name: 'Dumbbell Step Ups', group: 'Legs', pictogram: 'Lunge' },
  { name: 'Elevated Back Lunge', group: 'Legs', pictogram: 'Lunge' },
  { name: 'Fast Skipping', group: 'Legs', pictogram: 'Squat' },
  { name: 'Floor Glute-Ham Raise', group: 'Legs', pictogram: 'Squat' },
  { name: 'Flutter Kicks', group: 'Legs', pictogram: 'Squat' },
  { name: 'Foot-SMR', group: 'Legs', pictogram: 'Squat' },
  { name: 'Frankenstein Squat', group: 'Legs', pictogram: 'Squat' },
  { name: 'Freehand Jump Squat', group: 'Legs', pictogram: 'Squat' },
  { name: 'Frog Hops', group: 'Legs', pictogram: 'Squat' },
  { name: 'Front Barbell Squat', group: 'Legs', pictogram: 'Squat' },
  { name: 'Front Barbell Squat To A Bench', group: 'Legs', pictogram: 'Squat' },
  { name: 'Front Box Jump', group: 'Legs', pictogram: 'Squat' },
  { name: 'Front Cone Hops (or hurdle hops)', group: 'Legs', pictogram: 'Squat' },
  { name: 'Front Leg Raises', group: 'Legs', pictogram: 'LegRaise' },
  { name: 'Front Squat (Clean Grip)', group: 'Legs', pictogram: 'Squat' },
  { name: 'Front Squats With Two Kettlebells', group: 'Legs', pictogram: 'Squat' },
  { name: 'Glute Ham Raise', group: 'Legs', pictogram: 'Squat' },
  { name: 'Glute Kickback', group: 'Legs', pictogram: 'Pushdown' },
  { name: 'Goblet Squat', group: 'Legs', pictogram: 'Squat' },
  { name: 'Good Morning', group: 'Legs', pictogram: 'Hinge' },
  { name: 'Good Morning off Pins', group: 'Legs', pictogram: 'Hinge' },
  { name: 'Groin and Back Stretch', group: 'Legs', pictogram: 'Squat' },
  { name: 'Groiners', group: 'Legs', pictogram: 'Squat' },
  { name: 'Hack Squat', group: 'Legs', pictogram: 'Squat' },
  { name: 'Hamstring Stretch', group: 'Legs', pictogram: 'Squat' },
  { name: 'Hamstring-SMR', group: 'Legs', pictogram: 'Squat' },
  { name: 'Hang Clean', group: 'Legs', pictogram: 'Squat' },
  { name: 'Hang Clean - Below the Knees', group: 'Legs', pictogram: 'Squat' },
  { name: 'Hang Snatch', group: 'Legs', pictogram: 'Squat' },
  { name: 'Hang Snatch - Below Knees', group: 'Legs', pictogram: 'Squat' },
  { name: 'Hanging Bar Good Morning', group: 'Legs', pictogram: 'Hinge' },
  { name: 'Heaving Snatch Balance', group: 'Legs', pictogram: 'Squat' },
  { name: 'Hip Circles (prone)', group: 'Legs', pictogram: 'Squat' },
  { name: 'Hip Extension with Bands', group: 'Legs', pictogram: 'Squat' },
  { name: 'Hip Flexion with Band', group: 'Legs', pictogram: 'Squat' },
  { name: 'Hip Lift with Band', group: 'Legs', pictogram: 'Squat' },
  { name: 'Hurdle Hops', group: 'Legs', pictogram: 'Squat' },
  { name: 'IT Band and Glute Stretch', group: 'Legs', pictogram: 'Squat' },
  { name: 'Iliotibial Tract-SMR', group: 'Legs', pictogram: 'Squat' },
  { name: 'Inchworm', group: 'Legs', pictogram: 'Squat' },
  { name: 'Intermediate Groin Stretch', group: 'Legs', pictogram: 'Squat' },
  { name: 'Intermediate Hip Flexor and Quad Stretch', group: 'Legs', pictogram: 'Squat' },
  { name: 'Iron Crosses (stretch)', group: 'Legs', pictogram: 'Squat' },
  { name: 'Jefferson Squats', group: 'Legs', pictogram: 'Squat' },
  { name: 'Jerk Dip Squat', group: 'Legs', pictogram: 'Squat' },
  { name: 'Kettlebell Dead Clean', group: 'Legs', pictogram: 'Squat' },
  { name: 'Kettlebell Hang Clean', group: 'Legs', pictogram: 'Squat' },
  { name: 'Kettlebell One-Legged Deadlift', group: 'Legs', pictogram: 'Hinge' },
  { name: 'Kettlebell Pistol Squat', group: 'Legs', pictogram: 'Squat' },
  { name: 'Knee Across The Body', group: 'Legs', pictogram: 'Squat' },
  { name: 'Knee Circles', group: 'Legs', pictogram: 'Squat' },
  { name: 'Knee Tuck Jump', group: 'Legs', pictogram: 'Squat' },
  { name: 'Kneeling Hip Flexor', group: 'Legs', pictogram: 'Squat' },
  { name: 'Kneeling Jump Squat', group: 'Legs', pictogram: 'Squat' },
  { name: 'Kneeling Squat', group: 'Legs', pictogram: 'Squat' },
  { name: 'Lateral Bound', group: 'Legs', pictogram: 'Squat' },
  { name: 'Lateral Box Jump', group: 'Legs', pictogram: 'Squat' },
  { name: 'Lateral Cone Hops', group: 'Legs', pictogram: 'Squat' },
  { name: 'Leg Extensions', group: 'Legs', pictogram: 'LegExt' },
  { name: 'Leg Lift', group: 'Legs', pictogram: 'Squat' },
  { name: 'Leg Press', group: 'Legs', pictogram: 'LegPress' },
  { name: 'Leg-Up Hamstring Stretch', group: 'Legs', pictogram: 'Squat' },
  { name: 'Leverage Deadlift', group: 'Legs', pictogram: 'Hinge' },
  { name: 'Linear 3-Part Start Technique', group: 'Legs', pictogram: 'Squat' },
  { name: 'Linear Acceleration Wall Drill', group: 'Legs', pictogram: 'Squat' },
  { name: 'Linear Depth Jump', group: 'Legs', pictogram: 'Squat' },
  { name: 'Looking At Ceiling', group: 'Legs', pictogram: 'Squat' },
  { name: 'Lunge Pass Through', group: 'Legs', pictogram: 'Lunge' },
  { name: 'Lunge Sprint', group: 'Legs', pictogram: 'Lunge' },
  { name: 'Lying Bent Leg Groin', group: 'Legs', pictogram: 'Squat' },
  { name: 'Lying Crossover', group: 'Legs', pictogram: 'Fly' },
  { name: 'Lying Glute', group: 'Legs', pictogram: 'Squat' },
  { name: 'Lying Hamstring', group: 'Legs', pictogram: 'Squat' },
  { name: 'Lying Leg Curls', group: 'Legs', pictogram: 'LegCurl' },
  { name: 'Lying Machine Squat', group: 'Legs', pictogram: 'Squat' },
  { name: 'Lying Prone Quadriceps', group: 'Legs', pictogram: 'Squat' },
  { name: 'Monster Walk', group: 'Legs', pictogram: 'Squat' },
  { name: 'Mountain Climbers', group: 'Legs', pictogram: 'Squat' },
  { name: 'Moving Claw Series', group: 'Legs', pictogram: 'Squat' },
  { name: 'Muscle Snatch', group: 'Legs', pictogram: 'Squat' },
  { name: 'Narrow Stance Hack Squats', group: 'Legs', pictogram: 'Squat' },
  { name: 'Narrow Stance Leg Press', group: 'Legs', pictogram: 'LegPress' },
  { name: 'Narrow Stance Squats', group: 'Legs', pictogram: 'Squat' },
  { name: 'Natural Glute Ham Raise', group: 'Legs', pictogram: 'Squat' },
  { name: 'Olympic Squat', group: 'Legs', pictogram: 'Squat' },
  { name: 'On Your Side Quad Stretch', group: 'Legs', pictogram: 'Squat' },
  { name: 'On-Your-Back Quad Stretch', group: 'Legs', pictogram: 'Squat' },
  { name: 'One Half Locust', group: 'Legs', pictogram: 'Squat' },
  { name: 'One Knee To Chest', group: 'Legs', pictogram: 'Squat' },
  { name: 'One Leg Barbell Squat', group: 'Legs', pictogram: 'Squat' },
  { name: 'One-Arm Kettlebell Clean', group: 'Legs', pictogram: 'Squat' },
  { name: 'One-Arm Kettlebell Swings', group: 'Legs', pictogram: 'Squat' },
  { name: 'One-Arm Open Palm Kettlebell Clean', group: 'Legs', pictogram: 'Squat' },
  { name: 'One-Arm Overhead Kettlebell Squats', group: 'Legs', pictogram: 'Squat' },
  { name: 'One-Arm Side Deadlift', group: 'Legs', pictogram: 'Hinge' },
  { name: 'One-Legged Cable Kickback', group: 'Legs', pictogram: 'Pushdown' },
  { name: 'Open Palm Kettlebell Clean', group: 'Legs', pictogram: 'Squat' },
  { name: 'Overhead Squat', group: 'Legs', pictogram: 'Squat' },
  { name: 'Peroneals Stretch', group: 'Legs', pictogram: 'Squat' },
  { name: 'Peroneals-SMR', group: 'Legs', pictogram: 'Squat' },
  { name: 'Physioball Hip Bridge', group: 'Legs', pictogram: 'Squat' },
  { name: 'Piriformis-SMR', group: 'Legs', pictogram: 'Squat' },
  { name: 'Platform Hamstring Slides', group: 'Legs', pictogram: 'Squat' },
  { name: 'Plie Dumbbell Squat', group: 'Legs', pictogram: 'Squat' },
  { name: 'Posterior Tibialis Stretch', group: 'Legs', pictogram: 'Squat' },
  { name: 'Power Clean', group: 'Legs', pictogram: 'Squat' },
  { name: 'Power Clean from Blocks', group: 'Legs', pictogram: 'Squat' },
  { name: 'Power Jerk', group: 'Legs', pictogram: 'Squat' },
  { name: 'Power Snatch', group: 'Legs', pictogram: 'Squat' },
  { name: 'Power Snatch from Blocks', group: 'Legs', pictogram: 'Squat' },
  { name: 'Power Stairs', group: 'Legs', pictogram: 'Squat' },
  { name: 'Prone Manual Hamstring', group: 'Legs', pictogram: 'Squat' },
  { name: 'Pull Through', group: 'Legs', pictogram: 'Squat' },
  { name: 'Quad Stretch', group: 'Legs', pictogram: 'Squat' },
  { name: 'Quadriceps-SMR', group: 'Legs', pictogram: 'Squat' },
  { name: 'Quick Leap', group: 'Legs', pictogram: 'Squat' },
  { name: 'Rear Leg Raises', group: 'Legs', pictogram: 'LegRaise' },
  { name: 'Reverse Band Box Squat', group: 'Legs', pictogram: 'Squat' },
  { name: 'Reverse Band Power Squat', group: 'Legs', pictogram: 'Squat' },
  { name: 'Reverse Band Sumo Deadlift', group: 'Legs', pictogram: 'Hinge' },
  { name: 'Reverse Hyperextension', group: 'Legs', pictogram: 'Squat' },
  { name: 'Rickshaw Deadlift', group: 'Legs', pictogram: 'Hinge' },
  { name: 'Rocket Jump', group: 'Legs', pictogram: 'Squat' },
  { name: 'Rocking Standing Calf Raise', group: 'Legs', pictogram: 'Calf' },
  { name: 'Romanian Deadlift', group: 'Legs', pictogram: 'Hinge' },
  { name: 'Romanian Deadlift from Deficit', group: 'Legs', pictogram: 'Hinge' },
  { name: 'Runner\'s Stretch', group: 'Legs', pictogram: 'Cardio' },
  { name: 'Sandbag Load', group: 'Legs', pictogram: 'Squat' },
  { name: 'Scissors Jump', group: 'Legs', pictogram: 'Squat' },
  { name: 'Seated Band Hamstring Curl', group: 'Legs', pictogram: 'Curl' },
  { name: 'Seated Calf Raise', group: 'Legs', pictogram: 'Calf' },
  { name: 'Seated Calf Stretch', group: 'Legs', pictogram: 'Calf' },
  { name: 'Seated Floor Hamstring Stretch', group: 'Legs', pictogram: 'Squat' },
  { name: 'Seated Glute', group: 'Legs', pictogram: 'Squat' },
  { name: 'Seated Hamstring', group: 'Legs', pictogram: 'Squat' },
  { name: 'Seated Hamstring and Calf Stretch', group: 'Legs', pictogram: 'Calf' },
  { name: 'Seated Leg Curl', group: 'Legs', pictogram: 'LegCurl' },
  { name: 'Side Hop-Sprint', group: 'Legs', pictogram: 'Squat' },
  { name: 'Side Leg Raises', group: 'Legs', pictogram: 'LegRaise' },
  { name: 'Side Lying Groin Stretch', group: 'Legs', pictogram: 'Squat' },
  { name: 'Side Standing Long Jump', group: 'Legs', pictogram: 'Squat' },
  { name: 'Side to Side Box Shuffle', group: 'Legs', pictogram: 'Squat' },
  { name: 'Single Leg Butt Kick', group: 'Legs', pictogram: 'Squat' },
  { name: 'Single Leg Glute Bridge', group: 'Legs', pictogram: 'Hinge' },
  { name: 'Single Leg Push-off', group: 'Legs', pictogram: 'Squat' },
  { name: 'Single-Cone Sprint Drill', group: 'Legs', pictogram: 'Squat' },
  { name: 'Single-Leg High Box Squat', group: 'Legs', pictogram: 'Squat' },
  { name: 'Single-Leg Hop Progression', group: 'Legs', pictogram: 'Squat' },
  { name: 'Single-Leg Lateral Hop', group: 'Legs', pictogram: 'Squat' },
  { name: 'Single-Leg Leg Extension', group: 'Legs', pictogram: 'LegExt' },
  { name: 'Single-Leg Stride Jump', group: 'Legs', pictogram: 'Squat' },
  { name: 'Sit Squats', group: 'Legs', pictogram: 'Squat' },
  { name: 'Sled Drag - Harness', group: 'Legs', pictogram: 'Cardio' },
  { name: 'Sled Push', group: 'Legs', pictogram: 'Cardio' },
  { name: 'Smith Machine Calf Raise', group: 'Legs', pictogram: 'Calf' },
  { name: 'Smith Machine Hang Power Clean', group: 'Legs', pictogram: 'Squat' },
  { name: 'Smith Machine Leg Press', group: 'Legs', pictogram: 'LegPress' },
  { name: 'Smith Machine Pistol Squat', group: 'Legs', pictogram: 'Squat' },
  { name: 'Smith Machine Reverse Calf Raises', group: 'Legs', pictogram: 'Calf' },
  { name: 'Smith Machine Squat', group: 'Legs', pictogram: 'Squat' },
  { name: 'Smith Machine Stiff-Legged Deadlift', group: 'Legs', pictogram: 'Hinge' },
  { name: 'Smith Single-Leg Split Squat', group: 'Legs', pictogram: 'Squat' },
  { name: 'Snatch', group: 'Legs', pictogram: 'Squat' },
  { name: 'Snatch Balance', group: 'Legs', pictogram: 'Squat' },
  { name: 'Snatch Deadlift', group: 'Legs', pictogram: 'Hinge' },
  { name: 'Snatch Pull', group: 'Legs', pictogram: 'Squat' },
  { name: 'Snatch from Blocks', group: 'Legs', pictogram: 'Squat' },
  { name: 'Speed Box Squat', group: 'Legs', pictogram: 'Squat' },
  { name: 'Speed Squats', group: 'Legs', pictogram: 'Squat' },
  { name: 'Split Clean', group: 'Legs', pictogram: 'Squat' },
  { name: 'Split Jerk', group: 'Legs', pictogram: 'Squat' },
  { name: 'Split Jump', group: 'Legs', pictogram: 'Squat' },
  { name: 'Split Snatch', group: 'Legs', pictogram: 'Squat' },
  { name: 'Split Squat with Dumbbells', group: 'Legs', pictogram: 'Squat' },
  { name: 'Split Squats', group: 'Legs', pictogram: 'Squat' },
  { name: 'Squat Jerk', group: 'Legs', pictogram: 'Squat' },
  { name: 'Squat with Bands', group: 'Legs', pictogram: 'Squat' },
  { name: 'Squat with Chains', group: 'Legs', pictogram: 'Squat' },
  { name: 'Squat with Plate Movers', group: 'Legs', pictogram: 'Squat' },
  { name: 'Squats - With Bands', group: 'Legs', pictogram: 'Squat' },
  { name: 'Standing Barbell Calf Raise', group: 'Legs', pictogram: 'Calf' },
  { name: 'Standing Calf Raises', group: 'Legs', pictogram: 'Calf' },
  { name: 'Standing Dumbbell Calf Raise', group: 'Legs', pictogram: 'Calf' },
  { name: 'Standing Elevated Quad Stretch', group: 'Legs', pictogram: 'Squat' },
  { name: 'Standing Gastrocnemius Calf Stretch', group: 'Legs', pictogram: 'Calf' },
  { name: 'Standing Hamstring and Calf Stretch', group: 'Legs', pictogram: 'Calf' },
  { name: 'Standing Hip Circles', group: 'Legs', pictogram: 'Squat' },
  { name: 'Standing Hip Flexors', group: 'Legs', pictogram: 'Squat' },
  { name: 'Standing Leg Curl', group: 'Legs', pictogram: 'LegCurl' },
  { name: 'Standing Long Jump', group: 'Legs', pictogram: 'Squat' },
  { name: 'Standing Soleus And Achilles Stretch', group: 'Legs', pictogram: 'Squat' },
  { name: 'Standing Toe Touches', group: 'Legs', pictogram: 'Squat' },
  { name: 'Star Jump', group: 'Legs', pictogram: 'Squat' },
  { name: 'Step-up with Knee Raise', group: 'Legs', pictogram: 'Lunge' },
  { name: 'Stiff-Legged Barbell Deadlift', group: 'Legs', pictogram: 'Hinge' },
  { name: 'Stiff-Legged Dumbbell Deadlift', group: 'Legs', pictogram: 'Hinge' },
  { name: 'Stride Jump Crossover', group: 'Legs', pictogram: 'Fly' },
  { name: 'Sumo Deadlift', group: 'Legs', pictogram: 'Hinge' },
  { name: 'Sumo Deadlift with Bands', group: 'Legs', pictogram: 'Hinge' },
  { name: 'Sumo Deadlift with Chains', group: 'Legs', pictogram: 'Hinge' },
  { name: 'Suspended Split Squat', group: 'Legs', pictogram: 'Squat' },
  { name: 'The Straddle', group: 'Legs', pictogram: 'Squat' },
  { name: 'Thigh Abductor', group: 'Legs', pictogram: 'Squat' },
  { name: 'Thigh Adductor', group: 'Legs', pictogram: 'Squat' },
  { name: 'Tire Flip', group: 'Legs', pictogram: 'Squat' },
  { name: 'Trap Bar Deadlift', group: 'Legs', pictogram: 'Hinge' },
  { name: 'Upper Back-Leg Grab', group: 'Legs', pictogram: 'Squat' },
  { name: 'Vertical Swing', group: 'Legs', pictogram: 'Squat' },
  { name: 'Weighted Jump Squat', group: 'Legs', pictogram: 'Squat' },
  { name: 'Weighted Sissy Squat', group: 'Legs', pictogram: 'Squat' },
  { name: 'Weighted Squat', group: 'Legs', pictogram: 'Squat' },
  { name: 'Wide Stance Barbell Squat', group: 'Legs', pictogram: 'Squat' },
  { name: 'Wide Stance Stiff Legs', group: 'Legs', pictogram: 'Squat' },
  { name: 'Windmills', group: 'Legs', pictogram: 'Squat' },
  { name: 'World\'s Greatest Stretch', group: 'Legs', pictogram: 'Squat' },
  { name: 'Yoke Walk', group: 'Legs', pictogram: 'Squat' },
  { name: 'Zercher Squats', group: 'Legs', pictogram: 'Squat' },
  { name: 'Alternating Cable Shoulder Press', group: 'Shoulders', pictogram: 'OverheadPress' },
  { name: 'Alternating Deltoid Raise', group: 'Shoulders', pictogram: 'OverheadPress' },
  { name: 'Alternating Kettlebell Press', group: 'Shoulders', pictogram: 'OverheadPress' },
  { name: 'Anti-Gravity Press', group: 'Shoulders', pictogram: 'OverheadPress' },
  { name: 'Arm Circles', group: 'Shoulders', pictogram: 'OverheadPress' },
  { name: 'Arnold Dumbbell Press', group: 'Shoulders', pictogram: 'OverheadPress' },
  { name: 'Back Flyes - With Bands', group: 'Shoulders', pictogram: 'Fly' },
  { name: 'Backward Medicine Ball Throw', group: 'Shoulders', pictogram: 'Row' },
  { name: 'Band Pull Apart', group: 'Shoulders', pictogram: 'OverheadPress' },
  { name: 'Barbell Incline Shoulder Raise', group: 'Shoulders', pictogram: 'OverheadPress' },
  { name: 'Barbell Rear Delt Row', group: 'Shoulders', pictogram: 'Row' },
  { name: 'Barbell Shoulder Press', group: 'Shoulders', pictogram: 'OverheadPress' },
  { name: 'Barbell Shrug', group: 'Shoulders', pictogram: 'Shrug' },
  { name: 'Barbell Shrug Behind The Back', group: 'Shoulders', pictogram: 'Shrug' },
  { name: 'Battling Ropes', group: 'Shoulders', pictogram: 'OverheadPress' },
  { name: 'Bent Over Dumbbell Rear Delt Raise With Head On Bench', group: 'Shoulders', pictogram: 'RearDelt' },
  { name: 'Bent Over Low-Pulley Side Lateral', group: 'Shoulders', pictogram: 'LateralRaise' },
  { name: 'Bradford/Rocky Presses', group: 'Shoulders', pictogram: 'OverheadPress' },
  { name: 'Cable Internal Rotation', group: 'Shoulders', pictogram: 'Twist' },
  { name: 'Cable Rear Delt Fly', group: 'Shoulders', pictogram: 'Fly' },
  { name: 'Cable Rope Rear-Delt Rows', group: 'Shoulders', pictogram: 'Row' },
  { name: 'Cable Seated Lateral Raise', group: 'Shoulders', pictogram: 'LateralRaise' },
  { name: 'Cable Shoulder Press', group: 'Shoulders', pictogram: 'OverheadPress' },
  { name: 'Cable Shrugs', group: 'Shoulders', pictogram: 'Shrug' },
  { name: 'Calf-Machine Shoulder Shrug', group: 'Shoulders', pictogram: 'Calf' },
  { name: 'Car Drivers', group: 'Shoulders', pictogram: 'OverheadPress' },
  { name: 'Chair Upper Body Stretch', group: 'Shoulders', pictogram: 'OverheadPress' },
  { name: 'Chin To Chest Stretch', group: 'Shoulders', pictogram: 'OverheadPress' },
  { name: 'Circus Bell', group: 'Shoulders', pictogram: 'OverheadPress' },
  { name: 'Clean Shrug', group: 'Shoulders', pictogram: 'Shrug' },
  { name: 'Clean and Jerk', group: 'Shoulders', pictogram: 'OverheadPress' },
  { name: 'Clean and Press', group: 'Shoulders', pictogram: 'OverheadPress' },
  { name: 'Crucifix', group: 'Shoulders', pictogram: 'OverheadPress' },
  { name: 'Cuban Press', group: 'Shoulders', pictogram: 'OverheadPress' },
  { name: 'Double Kettlebell Jerk', group: 'Shoulders', pictogram: 'OverheadPress' },
  { name: 'Double Kettlebell Push Press', group: 'Shoulders', pictogram: 'OverheadPress' },
  { name: 'Double Kettlebell Snatch', group: 'Shoulders', pictogram: 'OverheadPress' },
  { name: 'Dumbbell Incline Shoulder Raise', group: 'Shoulders', pictogram: 'OverheadPress' },
  { name: 'Dumbbell Lying One-Arm Rear Lateral Raise', group: 'Shoulders', pictogram: 'LateralRaise' },
  { name: 'Dumbbell Lying Rear Lateral Raise', group: 'Shoulders', pictogram: 'LateralRaise' },
  { name: 'Dumbbell One-Arm Shoulder Press', group: 'Shoulders', pictogram: 'OverheadPress' },
  { name: 'Dumbbell One-Arm Upright Row', group: 'Shoulders', pictogram: 'Row' },
  { name: 'Dumbbell Raise', group: 'Shoulders', pictogram: 'OverheadPress' },
  { name: 'Dumbbell Scaption', group: 'Shoulders', pictogram: 'OverheadPress' },
  { name: 'Dumbbell Shoulder Press', group: 'Shoulders', pictogram: 'OverheadPress' },
  { name: 'Dumbbell Shrug', group: 'Shoulders', pictogram: 'Shrug' },
  { name: 'Elbow Circles', group: 'Shoulders', pictogram: 'OverheadPress' },
  { name: 'External Rotation', group: 'Shoulders', pictogram: 'Twist' },
  { name: 'External Rotation with Band', group: 'Shoulders', pictogram: 'Twist' },
  { name: 'External Rotation with Cable', group: 'Shoulders', pictogram: 'Twist' },
  { name: 'Face Pull', group: 'Shoulders', pictogram: 'RearDelt' },
  { name: 'Front Cable Raise', group: 'Shoulders', pictogram: 'OverheadPress' },
  { name: 'Front Dumbbell Raise', group: 'Shoulders', pictogram: 'OverheadPress' },
  { name: 'Front Incline Dumbbell Raise', group: 'Shoulders', pictogram: 'OverheadPress' },
  { name: 'Front Plate Raise', group: 'Shoulders', pictogram: 'OverheadPress' },
  { name: 'Front Two-Dumbbell Raise', group: 'Shoulders', pictogram: 'OverheadPress' },
  { name: 'Handstand Push-Ups', group: 'Shoulders', pictogram: 'PushUp' },
  { name: 'Internal Rotation with Band', group: 'Shoulders', pictogram: 'Twist' },
  { name: 'Iron Cross', group: 'Shoulders', pictogram: 'OverheadPress' },
  { name: 'Isometric Neck Exercise - Front And Back', group: 'Shoulders', pictogram: 'OverheadPress' },
  { name: 'Isometric Neck Exercise - Sides', group: 'Shoulders', pictogram: 'OverheadPress' },
  { name: 'Jerk Balance', group: 'Shoulders', pictogram: 'OverheadPress' },
  { name: 'Kettlebell Arnold Press', group: 'Shoulders', pictogram: 'OverheadPress' },
  { name: 'Kettlebell Pirate Ships', group: 'Shoulders', pictogram: 'OverheadPress' },
  { name: 'Kettlebell Seated Press', group: 'Shoulders', pictogram: 'OverheadPress' },
  { name: 'Kettlebell Seesaw Press', group: 'Shoulders', pictogram: 'OverheadPress' },
  { name: 'Kettlebell Sumo High Pull', group: 'Shoulders', pictogram: 'OverheadPress' },
  { name: 'Kettlebell Thruster', group: 'Shoulders', pictogram: 'OverheadPress' },
  { name: 'Kettlebell Turkish Get-Up (Lunge style)', group: 'Shoulders', pictogram: 'Lunge' },
  { name: 'Kettlebell Turkish Get-Up (Squat style)', group: 'Shoulders', pictogram: 'Squat' },
  { name: 'Kneeling Arm Drill', group: 'Shoulders', pictogram: 'OverheadPress' },
  { name: 'Landmine Linear Jammer', group: 'Shoulders', pictogram: 'OverheadPress' },
  { name: 'Lateral Raise - With Bands', group: 'Shoulders', pictogram: 'LateralRaise' },
  { name: 'Leverage Shoulder Press', group: 'Shoulders', pictogram: 'OverheadPress' },
  { name: 'Leverage Shrug', group: 'Shoulders', pictogram: 'Shrug' },
  { name: 'Log Lift', group: 'Shoulders', pictogram: 'OverheadPress' },
  { name: 'Low Pulley Row To Neck', group: 'Shoulders', pictogram: 'Row' },
  { name: 'Lying Face Down Plate Neck Resistance', group: 'Shoulders', pictogram: 'OverheadPress' },
  { name: 'Lying Face Up Plate Neck Resistance', group: 'Shoulders', pictogram: 'OverheadPress' },
  { name: 'Lying One-Arm Lateral Raise', group: 'Shoulders', pictogram: 'LateralRaise' },
  { name: 'Lying Rear Delt Raise', group: 'Shoulders', pictogram: 'RearDelt' },
  { name: 'Machine Shoulder (Military) Press', group: 'Shoulders', pictogram: 'OverheadPress' },
  { name: 'Medicine Ball Scoop Throw', group: 'Shoulders', pictogram: 'Row' },
  { name: 'Neck-SMR', group: 'Shoulders', pictogram: 'OverheadPress' },
  { name: 'One-Arm Incline Lateral Raise', group: 'Shoulders', pictogram: 'LateralRaise' },
  { name: 'One-Arm Kettlebell Clean and Jerk', group: 'Shoulders', pictogram: 'OverheadPress' },
  { name: 'One-Arm Kettlebell Jerk', group: 'Shoulders', pictogram: 'OverheadPress' },
  { name: 'One-Arm Kettlebell Military Press To The Side', group: 'Shoulders', pictogram: 'OverheadPress' },
  { name: 'One-Arm Kettlebell Para Press', group: 'Shoulders', pictogram: 'OverheadPress' },
  { name: 'One-Arm Kettlebell Push Press', group: 'Shoulders', pictogram: 'OverheadPress' },
  { name: 'One-Arm Kettlebell Snatch', group: 'Shoulders', pictogram: 'OverheadPress' },
  { name: 'One-Arm Kettlebell Split Jerk', group: 'Shoulders', pictogram: 'OverheadPress' },
  { name: 'One-Arm Kettlebell Split Snatch', group: 'Shoulders', pictogram: 'OverheadPress' },
  { name: 'One-Arm Side Laterals', group: 'Shoulders', pictogram: 'LateralRaise' },
  { name: 'Power Partials', group: 'Shoulders', pictogram: 'OverheadPress' },
  { name: 'Push Press', group: 'Shoulders', pictogram: 'OverheadPress' },
  { name: 'Push Press - Behind the Neck', group: 'Shoulders', pictogram: 'OverheadPress' },
  { name: 'Rack Delivery', group: 'Shoulders', pictogram: 'OverheadPress' },
  { name: 'Return Push from Stance', group: 'Shoulders', pictogram: 'OverheadPress' },
  { name: 'Reverse Flyes', group: 'Shoulders', pictogram: 'Fly' },
  { name: 'Reverse Flyes With External Rotation', group: 'Shoulders', pictogram: 'Fly' },
  { name: 'Reverse Machine Flyes', group: 'Shoulders', pictogram: 'Fly' },
  { name: 'Round The World Shoulder Stretch', group: 'Shoulders', pictogram: 'OverheadPress' },
  { name: 'Scapular Pull-Up', group: 'Shoulders', pictogram: 'PullDown' },
  { name: 'Seated Barbell Military Press', group: 'Shoulders', pictogram: 'OverheadPress' },
  { name: 'Seated Bent-Over Rear Delt Raise', group: 'Shoulders', pictogram: 'RearDelt' },
  { name: 'Seated Cable Shoulder Press', group: 'Shoulders', pictogram: 'OverheadPress' },
  { name: 'Seated Dumbbell Press', group: 'Shoulders', pictogram: 'OverheadPress' },
  { name: 'Seated Front Deltoid', group: 'Shoulders', pictogram: 'OverheadPress' },
  { name: 'Seated Head Harness Neck Resistance', group: 'Shoulders', pictogram: 'OverheadPress' },
  { name: 'Seated Side Lateral Raise', group: 'Shoulders', pictogram: 'LateralRaise' },
  { name: 'See-Saw Press (Alternating Side Press)', group: 'Shoulders', pictogram: 'OverheadPress' },
  { name: 'Shoulder Circles', group: 'Shoulders', pictogram: 'OverheadPress' },
  { name: 'Shoulder Press - With Bands', group: 'Shoulders', pictogram: 'OverheadPress' },
  { name: 'Shoulder Raise', group: 'Shoulders', pictogram: 'OverheadPress' },
  { name: 'Shoulder Stretch', group: 'Shoulders', pictogram: 'OverheadPress' },
  { name: 'Side Lateral Raise', group: 'Shoulders', pictogram: 'LateralRaise' },
  { name: 'Side Laterals to Front Raise', group: 'Shoulders', pictogram: 'LateralRaise' },
  { name: 'Side Neck Stretch', group: 'Shoulders', pictogram: 'OverheadPress' },
  { name: 'Side Wrist Pull', group: 'Shoulders', pictogram: 'OverheadPress' },
  { name: 'Single Dumbbell Raise', group: 'Shoulders', pictogram: 'OverheadPress' },
  { name: 'Single-Arm Linear Jammer', group: 'Shoulders', pictogram: 'OverheadPress' },
  { name: 'Sled Overhead Backward Walk', group: 'Shoulders', pictogram: 'Cardio' },
  { name: 'Sled Reverse Flye', group: 'Shoulders', pictogram: 'Fly' },
  { name: 'Smith Incline Shoulder Raise', group: 'Shoulders', pictogram: 'OverheadPress' },
  { name: 'Smith Machine Behind the Back Shrug', group: 'Shoulders', pictogram: 'Shrug' },
  { name: 'Smith Machine One-Arm Upright Row', group: 'Shoulders', pictogram: 'Row' },
  { name: 'Smith Machine Overhead Shoulder Press', group: 'Shoulders', pictogram: 'OverheadPress' },
  { name: 'Smith Machine Upright Row', group: 'Shoulders', pictogram: 'Row' },
  { name: 'Snatch Shrug', group: 'Shoulders', pictogram: 'Shrug' },
  { name: 'Standing Alternating Dumbbell Press', group: 'Shoulders', pictogram: 'OverheadPress' },
  { name: 'Standing Barbell Press Behind Neck', group: 'Shoulders', pictogram: 'OverheadPress' },
  { name: 'Standing Bradford Press', group: 'Shoulders', pictogram: 'OverheadPress' },
  { name: 'Standing Dumbbell Press', group: 'Shoulders', pictogram: 'OverheadPress' },
  { name: 'Standing Dumbbell Straight-Arm Front Delt Raise Above Head', group: 'Shoulders', pictogram: 'OverheadPress' },
  { name: 'Standing Dumbbell Upright Row', group: 'Shoulders', pictogram: 'Row' },
  { name: 'Standing Front Barbell Raise Over Head', group: 'Shoulders', pictogram: 'OverheadPress' },
  { name: 'Standing Low-Pulley Deltoid Raise', group: 'Shoulders', pictogram: 'OverheadPress' },
  { name: 'Standing Military Press', group: 'Shoulders', pictogram: 'OverheadPress' },
  { name: 'Standing Palm-In One-Arm Dumbbell Press', group: 'Shoulders', pictogram: 'OverheadPress' },
  { name: 'Standing Palms-In Dumbbell Press', group: 'Shoulders', pictogram: 'OverheadPress' },
  { name: 'Standing Two-Arm Overhead Throw', group: 'Shoulders', pictogram: 'Row' },
  { name: 'Straight Raises on Incline Bench', group: 'Shoulders', pictogram: 'OverheadPress' },
  { name: 'Two-Arm Kettlebell Clean', group: 'Shoulders', pictogram: 'OverheadPress' },
  { name: 'Two-Arm Kettlebell Jerk', group: 'Shoulders', pictogram: 'OverheadPress' },
  { name: 'Two-Arm Kettlebell Military Press', group: 'Shoulders', pictogram: 'OverheadPress' },
  { name: 'Upright Barbell Row', group: 'Shoulders', pictogram: 'Row' },
  { name: 'Upright Cable Row', group: 'Shoulders', pictogram: 'Row' },
  { name: 'Upright Row - With Bands', group: 'Shoulders', pictogram: 'Row' },
  { name: 'Upward Stretch', group: 'Shoulders', pictogram: 'OverheadPress' },
  { name: 'Band Skull Crusher', group: 'Triceps', pictogram: 'TricepExt' },
  { name: 'Bench Dips', group: 'Triceps', pictogram: 'Pushdown' },
  { name: 'Bench Press - Powerlifting', group: 'Triceps', pictogram: 'Press' },
  { name: 'Bench Press with Chains', group: 'Triceps', pictogram: 'Press' },
  { name: 'Board Press', group: 'Triceps', pictogram: 'Pushdown' },
  { name: 'Body Tricep Press', group: 'Triceps', pictogram: 'Pushdown' },
  { name: 'Body-Up', group: 'Triceps', pictogram: 'Pushdown' },
  { name: 'Cable Incline Triceps Extension', group: 'Triceps', pictogram: 'TricepExt' },
  { name: 'Cable Lying Triceps Extension', group: 'Triceps', pictogram: 'TricepExt' },
  { name: 'Cable One Arm Tricep Extension', group: 'Triceps', pictogram: 'Pushdown' },
  { name: 'Cable Rope Overhead Triceps Extension', group: 'Triceps', pictogram: 'TricepExt' },
  { name: 'Chain Handle Extension', group: 'Triceps', pictogram: 'Pushdown' },
  { name: 'Close-Grip Barbell Bench Press', group: 'Triceps', pictogram: 'Press' },
  { name: 'Close-Grip Dumbbell Press', group: 'Triceps', pictogram: 'Pushdown' },
  { name: 'Close-Grip EZ-Bar Press', group: 'Triceps', pictogram: 'Pushdown' },
  { name: 'Close-Grip Push-Up off of a Dumbbell', group: 'Triceps', pictogram: 'PushUp' },
  { name: 'Decline Close-Grip Bench To Skull Crusher', group: 'Triceps', pictogram: 'TricepExt' },
  { name: 'Decline Dumbbell Triceps Extension', group: 'Triceps', pictogram: 'TricepExt' },
  { name: 'Decline EZ Bar Triceps Extension', group: 'Triceps', pictogram: 'TricepExt' },
  { name: 'Dip Machine', group: 'Triceps', pictogram: 'Pushdown' },
  { name: 'Dips - Triceps Version', group: 'Triceps', pictogram: 'Pushdown' },
  { name: 'Dumbbell Floor Press', group: 'Triceps', pictogram: 'Press' },
  { name: 'Dumbbell One-Arm Triceps Extension', group: 'Triceps', pictogram: 'TricepExt' },
  { name: 'Dumbbell Tricep Extension -Pronated Grip', group: 'Triceps', pictogram: 'Pushdown' },
  { name: 'EZ-Bar Skullcrusher', group: 'Triceps', pictogram: 'Pushdown' },
  { name: 'Floor Press', group: 'Triceps', pictogram: 'Press' },
  { name: 'Floor Press with Chains', group: 'Triceps', pictogram: 'Press' },
  { name: 'Incline Barbell Triceps Extension', group: 'Triceps', pictogram: 'TricepExt' },
  { name: 'Incline Push-Up Close-Grip', group: 'Triceps', pictogram: 'PushUp' },
  { name: 'JM Press', group: 'Triceps', pictogram: 'Pushdown' },
  { name: 'Kneeling Cable Triceps Extension', group: 'Triceps', pictogram: 'TricepExt' },
  { name: 'Low Cable Triceps Extension', group: 'Triceps', pictogram: 'TricepExt' },
  { name: 'Lying Close-Grip Barbell Triceps Extension Behind The Head', group: 'Triceps', pictogram: 'TricepExt' },
  { name: 'Lying Close-Grip Barbell Triceps Press To Chin', group: 'Triceps', pictogram: 'Pushdown' },
  { name: 'Lying Dumbbell Tricep Extension', group: 'Triceps', pictogram: 'Pushdown' },
  { name: 'Lying Triceps Press', group: 'Triceps', pictogram: 'Pushdown' },
  { name: 'Machine Triceps Extension', group: 'Triceps', pictogram: 'TricepExt' },
  { name: 'One Arm Floor Press', group: 'Triceps', pictogram: 'Press' },
  { name: 'One Arm Pronated Dumbbell Triceps Extension', group: 'Triceps', pictogram: 'TricepExt' },
  { name: 'One Arm Supinated Dumbbell Triceps Extension', group: 'Triceps', pictogram: 'TricepExt' },
  { name: 'Overhead Triceps', group: 'Triceps', pictogram: 'Pushdown' },
  { name: 'Parallel Bar Dip', group: 'Triceps', pictogram: 'Pushdown' },
  { name: 'Pin Presses', group: 'Triceps', pictogram: 'Pushdown' },
  { name: 'Push-Ups - Close Triceps Position', group: 'Triceps', pictogram: 'PushUp' },
  { name: 'Reverse Band Bench Press', group: 'Triceps', pictogram: 'Press' },
  { name: 'Reverse Grip Triceps Pushdown', group: 'Triceps', pictogram: 'Pushdown' },
  { name: 'Reverse Triceps Bench Press', group: 'Triceps', pictogram: 'Press' },
  { name: 'Ring Dips', group: 'Triceps', pictogram: 'Pushdown' },
  { name: 'Seated Bent-Over One-Arm Dumbbell Triceps Extension', group: 'Triceps', pictogram: 'TricepExt' },
  { name: 'Seated Bent-Over Two-Arm Dumbbell Triceps Extension', group: 'Triceps', pictogram: 'TricepExt' },
  { name: 'Seated Triceps Press', group: 'Triceps', pictogram: 'Pushdown' },
  { name: 'Sled Overhead Triceps Extension', group: 'Triceps', pictogram: 'TricepExt' },
  { name: 'Smith Machine Close-Grip Bench Press', group: 'Triceps', pictogram: 'Press' },
  { name: 'Speed Band Overhead Triceps', group: 'Triceps', pictogram: 'Pushdown' },
  { name: 'Standing Bent-Over One-Arm Dumbbell Triceps Extension', group: 'Triceps', pictogram: 'TricepExt' },
  { name: 'Standing Bent-Over Two-Arm Dumbbell Triceps Extension', group: 'Triceps', pictogram: 'TricepExt' },
  { name: 'Standing Dumbbell Triceps Extension', group: 'Triceps', pictogram: 'TricepExt' },
  { name: 'Standing Low-Pulley One-Arm Triceps Extension', group: 'Triceps', pictogram: 'TricepExt' },
  { name: 'Standing One-Arm Dumbbell Triceps Extension', group: 'Triceps', pictogram: 'TricepExt' },
  { name: 'Standing Overhead Barbell Triceps Extension', group: 'Triceps', pictogram: 'TricepExt' },
  { name: 'Standing Towel Triceps Extension', group: 'Triceps', pictogram: 'TricepExt' },
  { name: 'Supine Chest Throw', group: 'Triceps', pictogram: 'Row' },
  { name: 'Tate Press', group: 'Triceps', pictogram: 'Pushdown' },
  { name: 'Tricep Dumbbell Kickback', group: 'Triceps', pictogram: 'Pushdown' },
  { name: 'Tricep Side Stretch', group: 'Triceps', pictogram: 'Pushdown' },
  { name: 'Triceps Overhead Extension with Rope', group: 'Triceps', pictogram: 'TricepExt' },
  { name: 'Triceps Pushdown', group: 'Triceps', pictogram: 'Pushdown' },
  { name: 'Triceps Pushdown - Rope Attachment', group: 'Triceps', pictogram: 'Pushdown' },
  { name: 'Triceps Pushdown - V-Bar Attachment', group: 'Triceps', pictogram: 'Pushdown' },
  { name: 'Triceps Stretch', group: 'Triceps', pictogram: 'Pushdown' },
  { name: 'Weighted Bench Dip', group: 'Triceps', pictogram: 'Pushdown' },
]

const GROUP_BY_NAME = new Map(EXERCISES.map((e) => [e.name.toLowerCase(), e.group]))

export function groupFor(name) {
  if (!name) return null
  return GROUP_BY_NAME.get(name.trim().toLowerCase()) || null
}

const PICTOGRAM_BY_NAME = new Map(EXERCISES.map((e) => [e.name.toLowerCase(), e.pictogram]))

// Returns the pictogram category key for a name, or null if it's not in the
// library (e.g. the user's own custom exercise name) — callers fall back to
// the plain muscle-group badge in that case, never a guessed/wrong pictogram.
export function pictogramFor(name) {
  if (!name) return null
  return PICTOGRAM_BY_NAME.get(name.trim().toLowerCase()) || null
}
// Shared muscle-group accent colors, used for badges and pictogram tiles.
export const GROUP_COLOR = {
  Chest: '#e5484d',
  Back: '#4e86f7',
  Shoulders: '#f5b93b',
  Legs: '#57a35f',
  Biceps: '#c77dff',
  Triceps: '#4dd0c8',
  Core: '#ff9f5b',
  Cardio: '#f06fa8',
  Other: '#767b84',
}
