// ~200 common gym exercises, curated and grouped for browsing, covering the
// equipment variants (machine / cable / dumbbell / barbell / smith / bodyweight)
// people actually encounter at a gym. No exact match to this list is ever
// required — WorkoutEditor keeps free-text entry as the source of truth,
// this only helps people find a name faster and lets the app infer which
// muscles a session trained.

export const GROUPS = ['Chest', 'Back', 'Shoulders', 'Legs', 'Biceps', 'Triceps', 'Core', 'Cardio']

export const EXERCISES = [
  // Chest
  { name: 'Flat Dumbbell Bench Press', group: 'Chest' },
  { name: 'Incline Dumbbell Bench Press', group: 'Chest' },
  { name: 'Decline Dumbbell Bench Press', group: 'Chest' },
  { name: 'Flat Barbell Bench Press', group: 'Chest' },
  { name: 'Incline Barbell Bench Press', group: 'Chest' },
  { name: 'Decline Barbell Bench Press', group: 'Chest' },
  { name: 'Smith Machine Bench Press', group: 'Chest' },
  { name: 'Smith Machine Incline Press', group: 'Chest' },
  { name: 'Machine Chest Press', group: 'Chest' },
  { name: 'Incline Machine Chest Press', group: 'Chest' },
  { name: 'Push-up', group: 'Chest' },
  { name: 'Incline Push-up', group: 'Chest' },
  { name: 'Wide Push-up', group: 'Chest' },
  { name: 'Pec Deck', group: 'Chest' },
  { name: 'Low Cable Chest Fly', group: 'Chest' },
  { name: 'High Cable Chest Fly', group: 'Chest' },
  { name: 'Mid Cable Chest Fly', group: 'Chest' },
  { name: 'Cable Crossover', group: 'Chest' },
  { name: 'Dumbbell Chest Fly', group: 'Chest' },
  { name: 'Incline Dumbbell Fly', group: 'Chest' },
  { name: 'Chest Dip', group: 'Chest' },
  { name: 'Landmine Press', group: 'Chest' },
  { name: 'Svend Press', group: 'Chest' },

  // Back
  { name: 'Deadlift', group: 'Back' },
  { name: 'Sumo Deadlift', group: 'Back' },
  { name: 'Rack Pull', group: 'Back' },
  { name: 'Pull-up', group: 'Back' },
  { name: 'Chin-up', group: 'Back' },
  { name: 'Assisted Pull-up', group: 'Back' },
  { name: 'Wide-Grip Lat Pulldown', group: 'Back' },
  { name: 'Close-Grip Lat Pulldown', group: 'Back' },
  { name: 'Reverse-Grip Lat Pulldown', group: 'Back' },
  { name: 'Single-Arm Lat Pulldown', group: 'Back' },
  { name: 'Seated Cable Row', group: 'Back' },
  { name: 'Wide-Grip Seated Row', group: 'Back' },
  { name: 'Single-Arm Cable Row', group: 'Back' },
  { name: 'Barbell Row', group: 'Back' },
  { name: 'Pendlay Row', group: 'Back' },
  { name: 'Single-Arm Dumbbell Row', group: 'Back' },
  { name: 'Chest-Supported Dumbbell Row', group: 'Back' },
  { name: 'Upper Back Machine Row', group: 'Back' },
  { name: 'T-Bar Row', group: 'Back' },
  { name: 'Smith Machine Row', group: 'Back' },
  { name: 'Hyperextension', group: 'Back' },
  { name: 'Straight-Arm Pulldown', group: 'Back' },
  { name: 'Good Morning', group: 'Back' },

  // Shoulders
  { name: 'Overhead Dumbbell Press', group: 'Shoulders' },
  { name: 'Overhead Barbell Press', group: 'Shoulders' },
  { name: 'Seated Dumbbell Shoulder Press', group: 'Shoulders' },
  { name: 'Machine Shoulder Press', group: 'Shoulders' },
  { name: 'Smith Machine Shoulder Press', group: 'Shoulders' },
  { name: 'Arnold Press', group: 'Shoulders' },
  { name: 'Push Press', group: 'Shoulders' },
  { name: 'Front Raise (Dumbbell)', group: 'Shoulders' },
  { name: 'Front Raise (Cable)', group: 'Shoulders' },
  { name: 'Front Raise (Plate)', group: 'Shoulders' },
  { name: 'Lateral Raise (Dumbbell)', group: 'Shoulders' },
  { name: 'Lateral Raise (Cable)', group: 'Shoulders' },
  { name: 'Lateral Raise (Machine)', group: 'Shoulders' },
  { name: 'Single-Arm Cable Lateral Raise', group: 'Shoulders' },
  { name: 'Face Pull (Cable)', group: 'Shoulders' },
  { name: 'Rear Delt Fly (Dumbbell)', group: 'Shoulders' },
  { name: 'Rear Delt Fly (Machine)', group: 'Shoulders' },
  { name: 'Reverse Pec Deck', group: 'Shoulders' },
  { name: 'Shrug (Dumbbell)', group: 'Shoulders' },
  { name: 'Shrug (Barbell)', group: 'Shoulders' },
  { name: 'Upright Row', group: 'Shoulders' },

  // Legs
  { name: 'Barbell Squat', group: 'Legs' },
  { name: 'Front Squat', group: 'Legs' },
  { name: 'Goblet Squat', group: 'Legs' },
  { name: 'Smith Machine Squat', group: 'Legs' },
  { name: 'Hack Squat', group: 'Legs' },
  { name: 'Bulgarian Split Squat', group: 'Legs' },
  { name: 'Lunges', group: 'Legs' },
  { name: 'Walking Lunges', group: 'Legs' },
  { name: 'Leg Press', group: 'Legs' },
  { name: 'Single-Leg Press', group: 'Legs' },
  { name: 'Leg Extension', group: 'Legs' },
  { name: 'Leg Curl (Seated)', group: 'Legs' },
  { name: 'Leg Curl (Lying)', group: 'Legs' },
  { name: 'Romanian Deadlift', group: 'Legs' },
  { name: 'Stiff-Leg Deadlift', group: 'Legs' },
  { name: 'Hip Thrust', group: 'Legs' },
  { name: 'Glute Bridge', group: 'Legs' },
  { name: 'Cable Kickback', group: 'Legs' },
  { name: 'Hip Abductor (Outer)', group: 'Legs' },
  { name: 'Hip Adductor (Inner)', group: 'Legs' },
  { name: 'Standing Calf Raise', group: 'Legs' },
  { name: 'Seated Calf Raise', group: 'Legs' },
  { name: 'Leg Press Calf Raise', group: 'Legs' },

  // Biceps
  { name: 'Dumbbell Bicep Curl', group: 'Biceps' },
  { name: 'Alternating Dumbbell Curl', group: 'Biceps' },
  { name: 'Barbell Bicep Curl', group: 'Biceps' },
  { name: 'EZ Bar Curl', group: 'Biceps' },
  { name: 'Cable Bicep Curl', group: 'Biceps' },
  { name: 'Rope Cable Curl', group: 'Biceps' },
  { name: 'Machine Bicep Curl', group: 'Biceps' },
  { name: 'Hammer Curl', group: 'Biceps' },
  { name: 'Cable Hammer Curl', group: 'Biceps' },
  { name: 'Preacher Curl', group: 'Biceps' },
  { name: 'Preacher Curl (Machine)', group: 'Biceps' },
  { name: 'Concentration Curl', group: 'Biceps' },
  { name: 'Incline Dumbbell Curl', group: 'Biceps' },
  { name: 'Spider Curl', group: 'Biceps' },
  { name: 'Wrist Curl', group: 'Biceps' },
  { name: 'Reverse Wrist Curl', group: 'Biceps' },

  // Triceps
  { name: 'Overhead Dumbbell Tricep Extension', group: 'Triceps' },
  { name: 'Overhead Barbell Tricep Extension', group: 'Triceps' },
  { name: 'EZ Bar Skull Crusher', group: 'Triceps' },
  { name: 'Dumbbell Skull Crusher', group: 'Triceps' },
  { name: 'Tricep Cable Pushdown', group: 'Triceps' },
  { name: 'Rope Tricep Pushdown', group: 'Triceps' },
  { name: 'Reverse-Grip Tricep Pushdown', group: 'Triceps' },
  { name: 'Overhead Cable Tricep Extension', group: 'Triceps' },
  { name: 'Single-Arm Cable Tricep Extension', group: 'Triceps' },
  { name: 'Close-Grip Bench Press', group: 'Triceps' },
  { name: 'Tricep Dip', group: 'Triceps' },
  { name: 'Bench Dip', group: 'Triceps' },
  { name: 'Machine Tricep Dip', group: 'Triceps' },
  { name: 'Tricep Kickback', group: 'Triceps' },
  { name: 'Diamond Push-up', group: 'Triceps' },

  // Core
  { name: 'Plank', group: 'Core' },
  { name: 'Side Plank', group: 'Core' },
  { name: 'Crunch', group: 'Core' },
  { name: 'Cable Crunch', group: 'Core' },
  { name: 'Machine Crunch', group: 'Core' },
  { name: 'Bicycle Crunch', group: 'Core' },
  { name: 'Russian Twist', group: 'Core' },
  { name: 'Hanging Leg Raise', group: 'Core' },
  { name: 'Hanging Knee Raise', group: 'Core' },
  { name: 'Lying Leg Raise', group: 'Core' },
  { name: 'Dragon Fly', group: 'Core' },
  { name: 'Cable Woodchopper', group: 'Core' },
  { name: 'Ab Wheel Rollout', group: 'Core' },
  { name: 'Sit-up', group: 'Core' },
  { name: 'Decline Sit-up', group: 'Core' },
  { name: 'Mountain Climber', group: 'Core' },
  { name: 'V-Up', group: 'Core' },

  // Cardio
  { name: 'Treadmill Run', group: 'Cardio' },
  { name: 'Treadmill Walk (Incline)', group: 'Cardio' },
  { name: 'Cycling', group: 'Cardio' },
  { name: 'Recumbent Bike', group: 'Cardio' },
  { name: 'Rowing Machine', group: 'Cardio' },
  { name: 'Stairmaster', group: 'Cardio' },
  { name: 'Elliptical', group: 'Cardio' },
  { name: 'Jump Rope', group: 'Cardio' },
  { name: 'Battle Ropes', group: 'Cardio' },
  { name: 'Sled Push', group: 'Cardio' },
  { name: 'Assault Bike', group: 'Cardio' },
]

// name (lowercased) -> group, for auto-deriving a session's muscle focus
// from the exercises actually logged in it.
const GROUP_BY_NAME = new Map(EXERCISES.map((e) => [e.name.toLowerCase(), e.group]))

export function groupFor(name) {
  if (!name) return null
  return GROUP_BY_NAME.get(name.trim().toLowerCase()) || null
}

export const IMAGE_BY_NAME = {
  'Arnold Press': 'arnold-press.jpg',
  'Barbell Row': 'barbell-row.jpg',
  'Barbell Squat': 'barbell-squat.jpg',
  'Cable Crossover': 'cable-crossover.jpg',
  'Cable Crunch': 'cable-crunch.jpg',
  'Chin-up': 'chin-up.jpg',
  'Close-Grip Bench Press': 'close-grip-bench-press.jpg',
  'Close-Grip Lat Pulldown': 'close-grip-lat-pulldown.jpg',
  'Concentration Curl': 'concentration-curl.jpg',
  'Crunch': 'crunch.jpg',
  'Deadlift': 'deadlift.jpg',
  'Decline Barbell Bench Press': 'decline-barbell-bench-press.jpg',
  'Decline Dumbbell Bench Press': 'decline-dumbbell-bench-press.jpg',
  'Dumbbell Bicep Curl': 'dumbbell-bicep-curl.jpg',
  'EZ Bar Curl': 'ez-bar-curl.jpg',
  'Elliptical': 'elliptical.jpg',
  'Front Raise (Cable)': 'front-raise-cable.jpg',
  'Front Raise (Dumbbell)': 'front-raise-dumbbell.jpg',
  'Front Raise (Plate)': 'front-raise-plate.jpg',
  'Front Squat': 'front-squat.jpg',
  'Glute Bridge': 'glute-bridge.jpg',
  'Goblet Squat': 'goblet-squat.jpg',
  'Good Morning': 'good-morning.jpg',
  'Hack Squat': 'hack-squat.jpg',
  'Hammer Curl': 'hammer-curl.jpg',
  'Hanging Leg Raise': 'hanging-leg-raise.jpg',
  'Hip Thrust': 'hip-thrust.jpg',
  'Incline Barbell Bench Press': 'incline-barbell-bench-press.jpg',
  'Incline Dumbbell Curl': 'incline-dumbbell-curl.jpg',
  'Incline Push-up': 'incline-push-up.jpg',
  'Lateral Raise (Cable)': 'lateral-raise-cable.jpg',
  'Lateral Raise (Dumbbell)': 'lateral-raise-dumbbell.jpg',
  'Leg Curl (Seated)': 'leg-curl-seated.jpg',
  'Leg Press': 'leg-press.jpg',
  'Lunges': 'lunges.jpg',
  'Lying Leg Raise': 'lying-leg-raise.jpg',
  'Machine Bicep Curl': 'machine-bicep-curl.jpg',
  'Machine Crunch': 'machine-crunch.jpg',
  'Plank': 'plank.jpg',
  'Preacher Curl': 'preacher-curl.jpg',
  'Pull-up': 'pull-up.jpg',
  'Push Press': 'push-press.jpg',
  'Push-up': 'push-up.jpg',
  'Recumbent Bike': 'recumbent-bike.jpg',
  'Romanian Deadlift': 'romanian-deadlift.jpg',
  'Russian Twist': 'russian-twist.jpg',
  'Seated Calf Raise': 'seated-calf-raise.jpg',
  'Shrug (Barbell)': 'shrug-barbell.jpg',
  'Shrug (Dumbbell)': 'shrug-dumbbell.jpg',
  'Sit-up': 'sit-up.jpg',
  'Sled Push': 'sled-push.jpg',
  'Smith Machine Bench Press': 'smith-machine-bench-press.jpg',
  'Smith Machine Incline Press': 'smith-machine-incline-press.jpg',
  'Smith Machine Row': 'smith-machine-row.jpg',
  'Smith Machine Shoulder Press': 'smith-machine-shoulder-press.jpg',
  'Smith Machine Squat': 'smith-machine-squat.jpg',
  'Spider Curl': 'spider-curl.jpg',
  'Stairmaster': 'stairmaster.jpg',
  'Standing Calf Raise': 'standing-calf-raise.jpg',
  'Straight-Arm Pulldown': 'straight-arm-pulldown.jpg',
  'Sumo Deadlift': 'sumo-deadlift.jpg',
  'Svend Press': 'svend-press.jpg',
  'T-Bar Row': 't-bar-row.jpg',
  'Tricep Kickback': 'tricep-kickback.jpg',
  'Upright Row': 'upright-row.jpg',
  'Wide Push-up': 'wide-push-up.jpg',
  'Wide-Grip Lat Pulldown': 'wide-grip-lat-pulldown.jpg',
  'Wrist Curl': 'wrist-curl.jpg',
}

export function imageFor(name) {
  if (!name) return null
  const file = IMAGE_BY_NAME[name.trim()]
  return file ? `/exercise-images/${file}` : null
}